# Type stub of the native module (bindings/python/src/lib.rs). Every argument and result that
# carries RDF is JSON text in the forms of crates/oxilite-core/src/json.rs.

from typing import Optional

class JsonLdError(ValueError):
    code: str

class NativeStore:
    def __init__(
        self,
        path: Optional[str] = None,
        library: Optional[str] = None,
        options: Optional[str] = None,
        read_only: bool = False,
    ) -> None: ...
    def query(self, sparql: str, options: Optional[str] = None) -> str: ...
    def explain(self, sparql: str) -> str: ...
    def update(self, sparql: str, base_iri: Optional[str] = None, prefixes: Optional[str] = None) -> None: ...
    def explain_update(self, sparql: str) -> str: ...
    def load(
        self,
        data: Optional[bytes],
        path: Optional[str],
        format: str,
        base_iri: Optional[str] = None,
        to_graph: Optional[str] = None,
        bulk: bool = False,
    ) -> None: ...
    def add(self, quads_json: str, bulk: bool = False) -> None: ...
    def remove(self, quads_json: str) -> None: ...
    def contains(self, quad_json: str) -> bool: ...
    def quads_for_pattern(
        self,
        subject: Optional[str] = None,
        predicate: Optional[str] = None,
        object: Optional[str] = None,
        graph_name: Optional[str] = None,
    ) -> str: ...
    def len(self) -> int: ...
    def dump(self, format: str, from_graph: Optional[str] = None) -> bytes: ...
    def named_graphs(self) -> str: ...
    def contains_named_graph(self, graph_json: str) -> bool: ...
    def add_graph(self, graph_json: str) -> None: ...
    def clear_graph(self, graph_json: str) -> None: ...
    def remove_graph(self, graph_json: str) -> None: ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def optimize(self) -> None: ...
    def backup(self, path: str) -> None: ...
    def cypher(self, query: str, params: Optional[str] = None, options: Optional[str] = None) -> str: ...
    def explain_cypher(self, query: str, params: Optional[str] = None, options: Optional[str] = None) -> str: ...
    def datalog(self, program: str, options: Optional[str] = None) -> str: ...
    def datalog_materialize(self, program: str, options: Optional[str] = None) -> str: ...
    def explain_datalog(self, program: str) -> str: ...
    def synalog(self, program: str, predicate: str, options: Optional[str] = None) -> str: ...
    def synalog_sql(self, program: str, predicate: str, options: Optional[str] = None) -> str: ...
    def materialize(self, reasonable: bool = False) -> int: ...
    def clear_inferences(self) -> None: ...
    def register_schema_graph(self, graph_json: str, role: str, registration: Optional[str] = None) -> None: ...
    def schema_graphs(self) -> str: ...
    def set_schema_graph_active(self, graph_json: str, active: bool) -> bool: ...
    def unregister_schema_graph(self, graph_json: str) -> bool: ...
    def drop_schema_graph(self, graph_json: str) -> int: ...
    def shape_index(self) -> str: ...
    def install_system_graphs(self) -> bool: ...
    def jsonld(self, op: str, args: str, options: Optional[str] = None) -> str: ...
    def versioning(self) -> str: ...
    def set_versioning(self, level: str, change: Optional[str] = None) -> str: ...
    def set_commit_info(self, info: Optional[str] = None) -> None: ...
    def history(self, limit: int) -> str: ...
    def changes(self, after: int, until: Optional[int] = None) -> str: ...
    def diff(self, from_: str, to: str) -> str: ...
    def purge(self, pattern: str, reason: Optional[str] = None) -> None: ...

def parse_rdf(
    data: Optional[bytes],
    path: Optional[str],
    format: str,
    base_iri: Optional[str] = None,
    without_named_graphs: bool = False,
    rename_blank_nodes: bool = False,
    lenient: bool = False,
) -> str: ...
def serialize_rdf(quads_json: str, format: str) -> bytes: ...
def serialize_results(output_json: str, format: str) -> bytes: ...
def parse_query_results(data: Optional[bytes], path: Optional[str], format: str) -> str: ...
def schema_sql(options: Optional[str] = None) -> str: ...
def check_iri(value: str) -> None: ...
def check_blank_node(value: str) -> None: ...
def check_language(tag: str) -> None: ...
def check_variable(name: str) -> None: ...
def new_blank_node_id() -> str: ...
def double_lexical(value: float) -> str: ...
