-- oxilite schema (generated by oxilite_core::schema::schema_sql)
CREATE TABLE IF NOT EXISTS oxilite_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS terms (id INTEGER PRIMARY KEY, lex TEXT NOT NULL, dt TEXT, lang TEXT, dir INTEGER, num REAL, nt INTEGER, ts REAL) STRICT;
CREATE INDEX IF NOT EXISTS terms_num ON terms(num) WHERE num IS NOT NULL;
CREATE INDEX IF NOT EXISTS terms_ts ON terms(ts) WHERE ts IS NOT NULL;
CREATE TRIGGER IF NOT EXISTS terms_collision BEFORE INSERT ON terms WHEN EXISTS (SELECT 1 FROM terms t WHERE t.id = NEW.id AND (t.lex IS NOT NEW.lex OR t.dt IS NOT NEW.dt OR t.lang IS NOT NEW.lang OR t.dir IS NOT NEW.dir)) BEGIN SELECT RAISE(ABORT, 'oxilite: term hash collision'); END;
CREATE TABLE IF NOT EXISTS triple_terms (id INTEGER PRIMARY KEY, s INTEGER NOT NULL, p INTEGER NOT NULL, o INTEGER NOT NULL, vk TEXT NOT NULL, sk TEXT NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS quads (s INTEGER NOT NULL, p INTEGER NOT NULL, o INTEGER NOT NULL, g INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (s, p, o, g)) WITHOUT ROWID, STRICT;
CREATE INDEX IF NOT EXISTS quads_posg ON quads(p, o, s, g);
CREATE INDEX IF NOT EXISTS quads_ospg ON quads(o, s, p, g);
CREATE TABLE IF NOT EXISTS graphs (id INTEGER PRIMARY KEY) STRICT;
CREATE TABLE IF NOT EXISTS stats_pred (p INTEGER PRIMARY KEY, triples INTEGER NOT NULL, distinct_s INTEGER NOT NULL, distinct_o INTEGER NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS stats_class (o INTEGER PRIMARY KEY, instances INTEGER NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS update_buffer (op INTEGER NOT NULL, s INTEGER NOT NULL, p INTEGER NOT NULL, o INTEGER NOT NULL, g INTEGER NOT NULL) STRICT;
CREATE TABLE IF NOT EXISTS oxilite_guard (graph_does_not_exist INTEGER CHECK (graph_does_not_exist IS NULL), graph_already_exists INTEGER CHECK (graph_already_exists IS NULL), computed_value_not_storable INTEGER CHECK (computed_value_not_storable IS NULL)) STRICT;
CREATE INDEX IF NOT EXISTS quads_gspo ON quads(g, s, p, o);
INSERT OR IGNORE INTO oxilite_meta(key, value) VALUES ('schema_version', '1'), ('graph_index', '1'), ('int_offset', '288230376151711744'), ('payload_bits', '59'), ('integer_tag', '6');
