// The D1 driver: runs the oxilite core's SQL requests on a Cloudflare D1 binding.
//
// The core (WebAssembly) never touches the database. Each operation is a job: the driver
// feeds it the response of every request it asks for, until it is done. Atomic requests
// become one `db.batch()` — D1's only transaction.

import {
  type CypherOptions,
  type CypherOutput,
  type DatalogMaterializeResult,
  type DatalogOptions,
  type DatalogOutput,
  type DatalogResult,
  type CypherResult,
  type CypherValue,
  type CredentialOptions,
  type DocumentFilter,
  type Drift,
  type JsonLdOptions,
  JsonLdError,
  type PresentationKeys,
  type StoredDocument,
  type Term,
  type TermJson,
  cypherResult,
  datalogResult,
  documentText,
  filterJson,
  fromJson,
  jsonLdError,
  storedDocument,
  type DumpOptions,
  type LoadData,
  type LoadOptions,
  type Output,
  type Quad,
  type QueryOptions,
  type QueryResult,
  type TermLike,
  type Change,
  type CommitInfo,
  type CommitRecord,
  type LevelChange,
  type Versioning,
  type VersionStatus,
  type GraphArg,
  type PropertyShapeEntry,
  type SchemaGraphEntry,
  type SchemaRegistration,
  type SchemaRole,
  graphJson,
  registrationJson,
  toSchemaGraphs,
  toShapeIndex,
  toChanges,
  loadDataToString,
  outputToResult,
  toJson,
} from "@oxilite/common";

/** The subset of the Cloudflare D1 binding API used by oxilite. */
export interface D1PreparedStatementLike {
  raw(): Promise<unknown[][]>;
}
export interface D1ResultLike {
  results?: Record<string, unknown>[];
  meta?: { changes?: number };
}
export interface D1DatabaseLike {
  prepare(sql: string): D1PreparedStatementLike;
  batch(statements: D1PreparedStatementLike[]): Promise<D1ResultLike[]>;
}

/** The wasm engine API (generated by wasm-bindgen from crates/oxilite-wasm). */
export interface WasmJob {
  step(response?: string | null): string;
  free?(): void;
}
export interface WasmEngine {
  open(): WasmJob;
  openExisting(): WasmJob;
  optimize(): WasmJob;
  query(sparql: string, options?: string | null): WasmJob;
  queryJson(sparql: string): WasmJob;
  explain(sparql: string): string;
  cypher(query: string, params?: string | null, options?: string | null): WasmJob;
  // Present only when the WebAssembly core was built with the `datalog` feature.
  datalog?(program: string, options?: string | null): WasmJob;
  datalog_materialize?(program: string, options?: string | null): WasmJob;
  explain_datalog?(program: string, options?: string | null): string;
  explainCypher(query: string, params?: string | null, options?: string | null): string;
  update(sparql: string, baseIri?: string | null): WasmJob;
  explainUpdate(sparql: string): string;
  load(data: string, format: string, base?: string | null, graph?: string | null): WasmJob;
  bulkLoad(data: string, format: string, base?: string | null, graph?: string | null): WasmJob;
  add(quads: string): WasmJob;
  delete(quads: string): WasmJob;
  has(quad: string): WasmJob;
  match(s?: string | null, p?: string | null, o?: string | null, g?: string | null): WasmJob;
  size(): WasmJob;
  dump(format: string, graph?: string | null): WasmJob;
  clear(): WasmJob;
  materialize(): WasmJob;
  clearInferences(): WasmJob;
  registerSchemaGraphSparql(graph: string, role: string, registration?: string | null): string;
  unregisterSchemaGraphSparql(graph: string): string;
  setSchemaGraphActiveSparql(graph: string, active: boolean): string;
  dropSchemaGraphSparql(graph: string): string;
  schemaGraphRegisteredSparql(graph: string): string;
  graphSizeSparql(graph: string): string;
  schemaGraphsSparql(): string;
  schemaGraphsFromOutput(output: string): string;
  systemGraphsSparql(): string;
  systemGraphsReadySparql(): string;
  shapeIndex(): WasmJob;
  schemaSql(): string;
  versioning(): WasmJob;
  setVersioning(level: string, change?: string | null): WasmJob;
  levelChangeSql(from: string, to: string, change?: string | null, state?: string | null): string;
  setCommitInfo(info?: string | null): void;
  history(limit: number): WasmJob;
  resolveVersion(version: string): WasmJob;
  changes(after: number, until?: number | null): WasmJob;
  diff(from: string, to: string): WasmJob;
  purge(pattern: string, reason?: string | null): WasmJob;
  jsonld(op: string, args: string, options?: string | null): WasmJob;
  jsonldSchemaSql(indexes?: string | null): string;
}
export type EngineConstructor = new (capabilities?: string | null, options?: string | null) => WasmEngine;

interface SqlStatement {
  sql: string;
}
interface SqlRequest {
  statements: SqlStatement[];
  mode: "read" | "atomic";
}
interface ResultSet {
  rows: unknown[][];
  changes: number;
}

/** A term hash collision (two different terms with the same 59-bit id). */
export class OxiliteCollisionError extends Error {}

function mapError(e: unknown): Error {
  const message = e instanceof Error ? e.message : String(e);
  if (message.includes("oxilite: term hash collision")) return new OxiliteCollisionError(message);
  if (message.includes("graph_does_not_exist")) return new Error("the graph does not exist");
  if (message.includes("graph_already_exists")) return new Error("the graph already exists");
  if (message.includes("jsonld_graphs.g")) {
    return new JsonLdError("graph-owned", `a graph of this document is already owned by another document: ${message}`);
  }
  if (message.includes("computed_value_not_storable")) {
    return new Error("an update template stores a computed non-integer value, which cannot be done on D1");
  }
  return e instanceof Error ? e : new Error(message);
}

export interface D1StoreOptions {
  /** Create the optional graph index (default true); only used when the schema is created. */
  graphIndex?: boolean;
  /** The schema was applied by a migration: open without DDL. */
  migrated?: boolean;
  /** Create the FTS5 full-text index over string literals (for `oxl:textMatch`). */
  textIndex?: boolean;
  /**
   * Versioning of a new store: `"off"` (default), `"stamped"` (a store clock and the tick that
   * added each quad) or `"log"` (an immutable change log: history and time travel). An existing
   * store keeps its level: change it with `setVersioning` or a migration.
   */
  versioning?: Versioning;
  /** With `"log"`: index the change log by predicate and object (faster as-of queries). */
  asOfIndex?: boolean;
  /** With `"stamped"` or `"log"`: index the tick that added each quad. */
  stampIndex?: boolean;
  /**
   * Install the system graphs in a blank store: the oxilite vocabulary in `<oxilite:vocabulary>`
   * and the schema registry's own description in `<oxilite:schema>` (default false, so a new
   * store is empty as in Oxigraph).
   */
  systemGraphs?: boolean;
}


/** An oxilite RDF store on a Cloudflare D1 database. */
export class D1Store {
  private constructor(
    readonly db: D1DatabaseLike,
    private readonly engine: WasmEngine,
  ) {}

  static async openWith(Engine: EngineConstructor, db: D1DatabaseLike, options: D1StoreOptions = {}): Promise<D1Store> {
    const engine = new Engine(
      null,
      JSON.stringify({
        graphIndex: options.graphIndex ?? true,
        textIndex: options.textIndex ?? false,
        versioning: options.versioning ?? "off",
        asOfIndex: options.asOfIndex ?? false,
        stampIndex: options.stampIndex ?? false,
        systemGraphs: options.systemGraphs ?? false,
      }),
    );
    const store = new D1Store(db, engine);
    await store.run(options.migrated ? engine.openExisting() : engine.open());
    return store;
  }

  private async execute(req: SqlRequest): Promise<ResultSet[]> {
    try {
      if (req.statements.length === 0) return [];
      if (req.mode === "read" && req.statements.length === 1) {
        const rows = await this.db.prepare((req.statements[0] as SqlStatement).sql).raw();
        return [{ rows, changes: 0 }];
      }
      const results = await this.db.batch(req.statements.map((s) => this.db.prepare(s.sql)));
      return results.map((r) => ({
        rows: (r.results ?? []).map((row) => Object.values(row)),
        changes: r.meta?.changes ?? 0,
      }));
    } catch (e) {
      throw mapError(e);
    }
  }

  private async run(job: WasmJob): Promise<Output> {
    try {
      let response: string | null = null;
      for (;;) {
        const step = JSON.parse(job.step(response)) as { execute?: SqlRequest; done?: Output };
        if (step.done !== undefined) return step.done;
        response = JSON.stringify(await this.execute(step.execute as SqlRequest));
      }
    } finally {
      job.free?.();
    }
  }

  /**
   * JSON-LD documents: each stored verbatim under a key (by default its `@id`), its RDF in a
   * named graph (by default the key). Every write is one D1 batch. Contexts load offline:
   * persist the ones your documents use with `putContext`.
   */
  jsonld(options: JsonLdOptions & { migrated?: boolean } = {}): D1JsonLdDocuments {
    return new D1JsonLdDocuments(this.jsonldCall(options));
  }

  /**
   * Verifiable Credentials (VCDM 1.1 and 2.0) stored under their `id`, RDF in the graph of the
   * same IRI; the W3C credential contexts are bundled. Proofs are not verified.
   */
  credentials(options: CredentialOptions & { migrated?: boolean } = {}): D1Credentials {
    return new D1Credentials(this.jsonldCall({ ...options, credentials: true }));
  }

  private jsonldCall(options: JsonLdOptions & { migrated?: boolean; credentials?: boolean }): AsyncCall {
    const { migrated, ...opts } = options;
    const json = JSON.stringify(opts);
    let ready: Promise<unknown> | null = migrated ? Promise.resolve() : null;
    const call = async (op: string, args: object): Promise<unknown> => {
      try {
        return await this.run(this.engine.jsonld(op, JSON.stringify(args), json));
      } catch (e) {
        throw jsonLdError(e);
      }
    };
    return async (op, args) => {
      ready ??= call("schema", {});
      await ready;
      return call(op, args);
    };
  }

  /**
   * A Cypher statement over the property-graph view of the dataset. Reads compile to SQL; a
   * writing statement reads, then applies its changes as one D1 batch.
   */
  async cypher(query: string, params: Record<string, CypherValue> = {}, options: CypherOptions = {}): Promise<CypherResult> {
    // A version is resolved once, so every read of the statement sees the same tick.
    const opts: Record<string, unknown> = { ...options };
    if (options.asOf !== undefined) {
      opts.asOfTick = await this.resolveVersion(options.asOf);
    }
    const out = (await this.run(this.engine.cypher(query, JSON.stringify(params), JSON.stringify(opts)))) as unknown as CypherOutput;
    return cypherResult(out);
  }

  /** The tick a version reference (`"HEAD~2"`, `"#42"`, `"@2026-09-01T00:00:00Z"`) designates. */
  async resolveVersion(version: string): Promise<number> {
    return ((await this.run(this.engine.resolveVersion(version))) as unknown as { value: number }).value;
  }

  /**
   * A Datalog program over the same quads: recursive rules with stratified negation,
   * constraints and aggregation. A program whose recursion is linear is one SQL statement, so
   * it costs one round trip here as it does anywhere; a component that has to be iterated
   * costs one per round, which `rounds` reports.
   */
  async datalog(program: string, options: DatalogOptions = {}): Promise<DatalogResult> {
    const datalog = this.requireDatalog(this.engine.datalog);
    const out = (await this.run(datalog(program, JSON.stringify(options)))) as unknown as DatalogOutput;
    return datalogResult(out);
  }

  /**
   * Stores what a Datalog program derives as inferences, in the table OWL 2 RL
   * materialization uses, so SPARQL and Cypher see them with `includeInferred`. The writes
   * are one D1 batch.
   */
  async datalogMaterialize(
    program: string,
    options: DatalogOptions = {},
  ): Promise<DatalogMaterializeResult> {
    const materialize = this.requireDatalog(this.engine.datalog_materialize);
    return (await this.run(
      materialize(program, JSON.stringify(options)),
    )) as unknown as DatalogMaterializeResult;
  }

  /** How a Datalog program runs: its strata, the strategy per recursive component, the SQL. */
  explainDatalog(program: string, options: DatalogOptions = {}): string {
    return this.requireDatalog(this.engine.explain_datalog)(program, JSON.stringify(options));
  }

  /**
   * The Datalog frontend is an opt-in feature of the WebAssembly core, so say which build is
   * needed rather than failing with "not a function".
   */
  private requireDatalog<T>(method: T | undefined): T {
    if (method === undefined) {
      throw new Error(
        "this build of the oxilite WebAssembly core has no Datalog frontend; rebuild it with the `datalog` feature",
      );
    }
    return (method as unknown as { bind(t: unknown): T }).bind(this.engine);
  }

  /** How a Cypher statement runs: its SPARQL, the SQL, and what runs in Rust. */
  explainCypher(query: string, params: Record<string, CypherValue> = {}, options: CypherOptions = {}): string {
    return this.engine.explainCypher(query, JSON.stringify(params), JSON.stringify(options));
  }

  /** SPARQL query: `Map[]` for SELECT, `boolean` for ASK, `Quad[]` for CONSTRUCT/DESCRIBE, or a string with `results_format`. */
  async query(query: string, options: QueryOptions = {}): Promise<QueryResult> {
    const js = {
      ...options,
      default_graph: options.default_graph
        ? Array.isArray(options.default_graph)
          ? options.default_graph.map(toJson)
          : toJson(options.default_graph)
        : undefined,
      named_graphs: options.named_graphs?.map(toJson),
    };
    return outputToResult(await this.run(this.engine.query(query, JSON.stringify(js))));
  }

  /** SPARQL query returning SPARQL 1.1 JSON results. */
  async queryJson(query: string): Promise<string> {
    const out = await this.run(this.engine.queryJson(query));
    return (out as { value: string }).value;
  }

  /** The SQL a query compiles to, with join orders and warnings. */
  explain(query: string): string {
    return this.engine.explain(query);
  }

  // ---------------------------------------------------------------------------- versioning

  /** The versioning level of the store and where its clock and history stand. */
  async versioning(): Promise<VersionStatus> {
    return (await this.run(this.engine.versioning())) as unknown as VersionStatus;
  }

  /**
   * Changes the versioning level. Upgrades keep every quad (the upgrade to `"log"` records the
   * whole store as its genesis commit); a downgrade freezes the history and stops the clock,
   * and deletes them only with `allowLoss`. On a production D1 database prefer a migration
   * (`npx oxilite-d1 versioning-migration`).
   */
  async setVersioning(level: Versioning, change: LevelChange = {}): Promise<VersionStatus> {
    return (await this.run(this.engine.setVersioning(level, JSON.stringify(change)))) as unknown as VersionStatus;
  }

  /** Author and message recorded on the commits of the following writes (until changed). */
  setCommitInfo(info: CommitInfo = {}): void {
    this.engine.setCommitInfo(JSON.stringify(info));
  }

  /** Runs `f` with `info` recorded on its writes. */
  async withCommit<T>(info: CommitInfo, f: (store: this) => Promise<T>): Promise<T> {
    this.setCommitInfo(info);
    try {
      return await f(this);
    } finally {
      this.setCommitInfo({});
    }
  }

  /** The latest commits and level changes, newest first. */
  async history(limit = 20): Promise<CommitRecord[]> {
    return (await this.run(this.engine.history(limit))) as unknown as CommitRecord[];
  }

  /** The changes after tick `after` (up to `until`), in order. */
  async changes(after = 0, until?: number): Promise<Change[]> {
    return toChanges(await this.run(this.engine.changes(after, until ?? null)));
  }

  /** The net difference between two versions (`"HEAD~1"`, `"#42"`, `"@2026-09-01T00:00:00Z"`). */
  async diff(from: string, to = "HEAD"): Promise<Change[]> {
    return toChanges(await this.run(this.engine.diff(from, to)));
  }

  /**
   * Removes the quads matching the pattern from the store and from its whole history, for
   * erasure requests; the purge is recorded without the removed content.
   */
  async purge(
    pattern: { subject?: TermLike; predicate?: TermLike; object?: TermLike; graph?: TermLike },
    reason?: string,
  ): Promise<void> {
    const json: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(pattern)) if (v) json[k] = toJson(v as TermLike);
    await this.run(this.engine.purge(JSON.stringify(json), reason ?? null));
  }

  /** SPARQL update, applied atomically in one D1 batch. */
  async update(update: string, options: { base_iri?: string } = {}): Promise<void> {
    await this.run(this.engine.update(update, options.base_iri ?? null));
  }

  /** How an update runs (SQL per operation). */
  explainUpdate(update: string): string {
    return this.engine.explainUpdate(update);
  }

  /** Loads RDF atomically (one batch); use `bulkLoad` for large documents. */
  async load(data: LoadData, options: LoadOptions): Promise<void> {
    const graph = options.to_graph_name ? JSON.stringify(toJson(options.to_graph_name)) : null;
    const text = loadDataToString(data);
    const job = options.no_transaction
      ? this.engine.bulkLoad(text, options.format, options.base_iri ?? null, graph)
      : this.engine.load(text, options.format, options.base_iri ?? null, graph);
    await this.run(job);
  }

  /** Loads RDF in several batches (not atomic) and refreshes planner statistics. */
  async bulkLoad(data: LoadData, options: LoadOptions): Promise<void> {
    await this.load(data, { ...options, no_transaction: true });
  }

  /** Serializes the dataset or one graph. */
  async dump(options: DumpOptions): Promise<string> {
    const graph = options.from_graph_name ? JSON.stringify(toJson(options.from_graph_name)) : null;
    return ((await this.run(this.engine.dump(options.format, graph))) as { value: string }).value;
  }

  async add(quad: TermLike): Promise<void> {
    await this.run(this.engine.add(JSON.stringify([toJson(quad)])));
  }

  /** Inserts many quads atomically. */
  async addAll(quads: TermLike[]): Promise<void> {
    await this.run(this.engine.add(JSON.stringify(quads.map(toJson))));
  }

  async delete(quad: TermLike): Promise<void> {
    await this.run(this.engine.delete(JSON.stringify([toJson(quad)])));
  }

  async has(quad: TermLike): Promise<boolean> {
    return ((await this.run(this.engine.has(JSON.stringify(toJson(quad))))) as { value: boolean }).value;
  }

  async match(subject?: TermLike | null, predicate?: TermLike | null, object?: TermLike | null, graph?: TermLike | null): Promise<Quad[]> {
    const j = (t?: TermLike | null) => (t ? JSON.stringify(toJson(t)) : null);
    return outputToResult(await this.run(this.engine.match(j(subject), j(predicate), j(object), j(graph)))) as Quad[];
  }

  /** Number of quads. */
  async size(): Promise<number> {
    return ((await this.run(this.engine.size())) as { value: number }).value;
  }

  /**
   * Computes the OWL 2 RL closure into a separate inference table with SQL rules (one D1
   * batch per round; not atomic as a whole). Query it with `include_inferred: true`.
   * Returns the number of inferred triples.
   */
  async materialize(): Promise<number> {
    return ((await this.run(this.engine.materialize())) as { value: number }).value;
  }

  /** Removes every materialized inference. */
  async clearInferences(): Promise<void> {
    await this.run(this.engine.clearInferences());
  }

  // The schema registry is RDF in <oxilite:schema>: the core builds the portable SPARQL, and
  // this driver runs it like any other query or update.

  /**
   * Declares a graph to hold an ontology, SHACL shapes or a ShEx schema, and (`appliesTo`) the
   * graphs it describes. One atomic batch that also rebuilds the reasoning closure and the
   * shape index; the graph's triples stay where they are.
   */
  async registerSchemaGraph(graph: GraphArg, role: SchemaRole, registration: SchemaRegistration = {}): Promise<void> {
    await this.update(this.engine.registerSchemaGraphSparql(graphJson(graph), role, registrationJson(registration)));
  }

  /** The schema registry, ordered by role and graph. */
  async schemaGraphs(): Promise<SchemaGraphEntry[]> {
    const out = await this.run(this.engine.query(this.engine.schemaGraphsSparql()));
    return toSchemaGraphs(JSON.parse(this.engine.schemaGraphsFromOutput(JSON.stringify(out))));
  }

  private async registered(graph: GraphArg): Promise<boolean> {
    return (await this.query(this.engine.schemaGraphRegisteredSparql(graphJson(graph)))) === true;
  }

  /** Activates or deactivates a registration; returns whether one was found. */
  async setSchemaGraphActive(graph: GraphArg, active: boolean): Promise<boolean> {
    if (!(await this.registered(graph))) return false;
    await this.update(this.engine.setSchemaGraphActiveSparql(graphJson(graph), active));
    return true;
  }

  /** Removes a registration, keeping the graph's triples; returns whether one was found. */
  async unregisterSchemaGraph(graph: GraphArg): Promise<boolean> {
    if (!(await this.registered(graph))) return false;
    await this.update(this.engine.unregisterSchemaGraphSparql(graphJson(graph)));
    return true;
  }

  /** Removes a registration and every quad of its graph; returns how many quads it held. */
  async dropSchemaGraph(graph: GraphArg): Promise<number> {
    const rows = (await this.query(this.engine.graphSizeSparql(graphJson(graph)))) as Map<string, Term>[];
    await this.update(this.engine.dropSchemaGraphSparql(graphJson(graph)));
    return Number(rows[0]?.get("n")?.value ?? 0);
  }

  /**
   * Installs or refreshes the system graphs (`<oxilite:vocabulary>`, `<oxilite:schema>`'s own
   * description) in an existing database; returns `false` when they were already current.
   */
  async installSystemGraphs(): Promise<boolean> {
    if ((await this.query(this.engine.systemGraphsReadySparql())) === true) return false;
    await this.update(this.engine.systemGraphsSparql());
    return true;
  }

  /** The compiled SHACL property shapes of the registered shapes graphs. */
  async shapeIndex(): Promise<PropertyShapeEntry[]> {
    return toShapeIndex(await this.run(this.engine.shapeIndex()));
  }

  /** Refreshes planner statistics (run after large imports). */
  async optimize(): Promise<void> {
    await this.run(this.engine.optimize());
  }

  async clear(): Promise<void> {
    await this.run(this.engine.clear());
  }

  /** The schema SQL of this store (for `wrangler d1 migrations`). */
  schemaSql(): string {
    return this.engine.schemaSql();
  }
}

type AsyncCall = (op: string, args: object) => Promise<unknown>;

/** JSON-LD documents of a D1 store (see `D1Store.jsonld`). */
export class D1JsonLdDocuments {
  constructor(private readonly call: AsyncCall) {}

  /** Stores a document (replacing one with the same key) and returns its key. JSON text is stored byte for byte. */
  async put(document: string | object, key?: string): Promise<string> {
    return (await this.putAll([{ document, key }]))[0] as string;
  }

  /** Stores several documents in one D1 batch; returns their keys. */
  async putAll(documents: { document: string | object; key?: string }[]): Promise<string[]> {
    const out = (await this.call("put", {
      documents: documents.map((d) => ({ json: documentText(d.document), key: d.key })),
    })) as { keys: string[] };
    return out.keys;
  }

  async get(key: string): Promise<StoredDocument | null> {
    return storedDocument((await this.call("get", { key })) as Record<string, unknown> | null);
  }

  /** Removes a document and the graphs it owns; false when it was not stored. */
  async remove(key: string): Promise<boolean> {
    return (await this.call("remove", { key })) as boolean;
  }

  async list(options: { after?: string; limit?: number } = {}): Promise<StoredDocument[]> {
    return ((await this.call("list", options)) as Record<string, unknown>[]).map((d) => storedDocument(d) as StoredDocument);
  }

  async find(filter: DocumentFilter = {}): Promise<StoredDocument[]> {
    return ((await this.call("find", filterJson(filter))) as Record<string, unknown>[]).map((d) => storedDocument(d) as StoredDocument);
  }

  async graphs(key: string): Promise<Term[]> {
    return ((await this.call("graphs", { key })) as TermJson[]).map(fromJson);
  }

  async documentForGraph(graph: TermLike): Promise<StoredDocument | null> {
    return storedDocument((await this.call("documentForGraph", { graph: toJson(graph) })) as Record<string, unknown> | null);
  }

  /** Persists a context in D1, so documents that reference `iri` convert offline. */
  async putContext(iri: string, context: object | string): Promise<void> {
    await this.call("putContext", { iri, context });
  }

  async removeContext(iri: string): Promise<void> {
    await this.call("removeContext", { iri });
  }

  async contexts(): Promise<string[]> {
    return (await this.call("contexts", {})) as string[];
  }

  async rebuild(key: string): Promise<boolean> {
    return (await this.call("rebuild", { key })) as boolean;
  }

  async check(): Promise<Drift[]> {
    return (await this.call("check", {})) as Drift[];
  }
}

/** Verifiable Credentials of a D1 store (see `D1Store.credentials`). */
export class D1Credentials {
  readonly documents: D1JsonLdDocuments;

  constructor(private readonly call: AsyncCall) {
    this.documents = new D1JsonLdDocuments(call);
  }

  /** Checks and stores a credential; returns its key. */
  async put(credential: string | object, key?: string): Promise<string> {
    return (await this.call("putCredential", { json: documentText(credential), key })) as string;
  }

  /** Stores a presentation and each credential it embeds, in one D1 batch. */
  async putPresentation(presentation: string | object): Promise<PresentationKeys> {
    return (await this.call("putPresentation", { json: documentText(presentation) })) as PresentationKeys;
  }

  get(key: string): Promise<StoredDocument | null> {
    return this.documents.get(key);
  }

  remove(key: string): Promise<boolean> {
    return this.documents.remove(key);
  }

  async find(filter: DocumentFilter = {}): Promise<StoredDocument[]> {
    return ((await this.call("find", filterJson(filter))) as Record<string, unknown>[]).map((d) => storedDocument(d) as StoredDocument);
  }
}
