// The D1 driver: runs the oxilite core's SQL requests on a Cloudflare D1 binding.
//
// The core (WebAssembly) never touches the database. Each operation is a job: the driver
// feeds it the response of every request it asks for, until it is done. Atomic requests
// become one `db.batch()` — D1's only transaction.

import {
  type DumpOptions,
  type LoadData,
  type LoadOptions,
  type Output,
  type Quad,
  type QueryOptions,
  type QueryResult,
  type TermLike,
  loadDataToString,
  outputToResult,
  toJson,
} from "@oxilite/common";

/** The subset of the Cloudflare D1 binding API used by oxilite. */
export interface D1PreparedStatementLike {
  raw(): Promise<unknown[][]>;
}
export interface D1ResultLike {
  results?: Record<string, unknown>[];
  meta?: { changes?: number };
}
export interface D1DatabaseLike {
  prepare(sql: string): D1PreparedStatementLike;
  batch(statements: D1PreparedStatementLike[]): Promise<D1ResultLike[]>;
}

/** The wasm engine API (generated by wasm-bindgen from crates/oxilite-wasm). */
export interface WasmJob {
  step(response?: string | null): string;
  free?(): void;
}
export interface WasmEngine {
  open(): WasmJob;
  openExisting(): WasmJob;
  optimize(): WasmJob;
  query(sparql: string, options?: string | null): WasmJob;
  queryJson(sparql: string): WasmJob;
  explain(sparql: string): string;
  update(sparql: string, baseIri?: string | null): WasmJob;
  explainUpdate(sparql: string): string;
  load(data: string, format: string, base?: string | null, graph?: string | null): WasmJob;
  bulkLoad(data: string, format: string, base?: string | null, graph?: string | null): WasmJob;
  add(quads: string): WasmJob;
  delete(quads: string): WasmJob;
  has(quad: string): WasmJob;
  match(s?: string | null, p?: string | null, o?: string | null, g?: string | null): WasmJob;
  size(): WasmJob;
  dump(format: string, graph?: string | null): WasmJob;
  clear(): WasmJob;
  schemaSql(): string;
}
export type EngineConstructor = new (capabilities?: string | null, options?: string | null) => WasmEngine;

interface SqlStatement {
  sql: string;
}
interface SqlRequest {
  statements: SqlStatement[];
  mode: "read" | "atomic";
}
interface ResultSet {
  rows: unknown[][];
  changes: number;
}

/** A term hash collision (two different terms with the same 59-bit id). */
export class OxiliteCollisionError extends Error {}

function mapError(e: unknown): Error {
  const message = e instanceof Error ? e.message : String(e);
  if (message.includes("oxilite: term hash collision")) return new OxiliteCollisionError(message);
  if (message.includes("graph_does_not_exist")) return new Error("the graph does not exist");
  if (message.includes("graph_already_exists")) return new Error("the graph already exists");
  if (message.includes("computed_value_not_storable")) {
    return new Error("an update template stores a computed non-integer value, which cannot be done on D1");
  }
  return e instanceof Error ? e : new Error(message);
}

export interface D1StoreOptions {
  /** Create the optional graph index (default true); only used when the schema is created. */
  graphIndex?: boolean;
  /** The schema was applied by a migration: open without DDL. */
  migrated?: boolean;
}

/** An oxilite RDF store on a Cloudflare D1 database. */
export class D1Store {
  private constructor(
    readonly db: D1DatabaseLike,
    private readonly engine: WasmEngine,
  ) {}

  static async openWith(Engine: EngineConstructor, db: D1DatabaseLike, options: D1StoreOptions = {}): Promise<D1Store> {
    const engine = new Engine(null, JSON.stringify({ graphIndex: options.graphIndex ?? true }));
    const store = new D1Store(db, engine);
    await store.run(options.migrated ? engine.openExisting() : engine.open());
    return store;
  }

  private async execute(req: SqlRequest): Promise<ResultSet[]> {
    try {
      if (req.statements.length === 0) return [];
      if (req.mode === "read" && req.statements.length === 1) {
        const rows = await this.db.prepare((req.statements[0] as SqlStatement).sql).raw();
        return [{ rows, changes: 0 }];
      }
      const results = await this.db.batch(req.statements.map((s) => this.db.prepare(s.sql)));
      return results.map((r) => ({
        rows: (r.results ?? []).map((row) => Object.values(row)),
        changes: r.meta?.changes ?? 0,
      }));
    } catch (e) {
      throw mapError(e);
    }
  }

  private async run(job: WasmJob): Promise<Output> {
    try {
      let response: string | null = null;
      for (;;) {
        const step = JSON.parse(job.step(response)) as { execute?: SqlRequest; done?: Output };
        if (step.done !== undefined) return step.done;
        response = JSON.stringify(await this.execute(step.execute as SqlRequest));
      }
    } finally {
      job.free?.();
    }
  }

  /** SPARQL query: `Map[]` for SELECT, `boolean` for ASK, `Quad[]` for CONSTRUCT/DESCRIBE, or a string with `results_format`. */
  async query(query: string, options: QueryOptions = {}): Promise<QueryResult> {
    const js = {
      ...options,
      default_graph: options.default_graph
        ? Array.isArray(options.default_graph)
          ? options.default_graph.map(toJson)
          : toJson(options.default_graph)
        : undefined,
      named_graphs: options.named_graphs?.map(toJson),
    };
    return outputToResult(await this.run(this.engine.query(query, JSON.stringify(js))));
  }

  /** SPARQL query returning SPARQL 1.1 JSON results. */
  async queryJson(query: string): Promise<string> {
    const out = await this.run(this.engine.queryJson(query));
    return (out as { value: string }).value;
  }

  /** The SQL a query compiles to, with join orders and warnings. */
  explain(query: string): string {
    return this.engine.explain(query);
  }

  /** SPARQL update, applied atomically in one D1 batch. */
  async update(update: string, options: { base_iri?: string } = {}): Promise<void> {
    await this.run(this.engine.update(update, options.base_iri ?? null));
  }

  /** How an update runs (SQL per operation). */
  explainUpdate(update: string): string {
    return this.engine.explainUpdate(update);
  }

  /** Loads RDF atomically (one batch); use `bulkLoad` for large documents. */
  async load(data: LoadData, options: LoadOptions): Promise<void> {
    const graph = options.to_graph_name ? JSON.stringify(toJson(options.to_graph_name)) : null;
    const text = loadDataToString(data);
    const job = options.no_transaction
      ? this.engine.bulkLoad(text, options.format, options.base_iri ?? null, graph)
      : this.engine.load(text, options.format, options.base_iri ?? null, graph);
    await this.run(job);
  }

  /** Loads RDF in several batches (not atomic) and refreshes planner statistics. */
  async bulkLoad(data: LoadData, options: LoadOptions): Promise<void> {
    await this.load(data, { ...options, no_transaction: true });
  }

  /** Serializes the dataset or one graph. */
  async dump(options: DumpOptions): Promise<string> {
    const graph = options.from_graph_name ? JSON.stringify(toJson(options.from_graph_name)) : null;
    return ((await this.run(this.engine.dump(options.format, graph))) as { value: string }).value;
  }

  async add(quad: TermLike): Promise<void> {
    await this.run(this.engine.add(JSON.stringify([toJson(quad)])));
  }

  /** Inserts many quads atomically. */
  async addAll(quads: TermLike[]): Promise<void> {
    await this.run(this.engine.add(JSON.stringify(quads.map(toJson))));
  }

  async delete(quad: TermLike): Promise<void> {
    await this.run(this.engine.delete(JSON.stringify([toJson(quad)])));
  }

  async has(quad: TermLike): Promise<boolean> {
    return ((await this.run(this.engine.has(JSON.stringify(toJson(quad))))) as { value: boolean }).value;
  }

  async match(subject?: TermLike | null, predicate?: TermLike | null, object?: TermLike | null, graph?: TermLike | null): Promise<Quad[]> {
    const j = (t?: TermLike | null) => (t ? JSON.stringify(toJson(t)) : null);
    return outputToResult(await this.run(this.engine.match(j(subject), j(predicate), j(object), j(graph)))) as Quad[];
  }

  /** Number of quads. */
  async size(): Promise<number> {
    return ((await this.run(this.engine.size())) as { value: number }).value;
  }

  /** Refreshes planner statistics (run after large imports). */
  async optimize(): Promise<void> {
    await this.run(this.engine.optimize());
  }

  async clear(): Promise<void> {
    await this.run(this.engine.clear());
  }

  /** The schema SQL of this store (for `wrangler d1 migrations`). */
  schemaSql(): string {
    return this.engine.schemaSql();
  }
}
